In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
set1 = pd.read_csv('flights_2010_000000000000.gzip',compression='gzip',parse_dates=True,index_col='date')

set2 = pd.read_csv('flights_2010_000000000001.gzip',compression='gzip',parse_dates=True,index_col='date')

set3 = pd.read_csv('flights_2010_000000000002.gzip',compression='gzip',parse_dates=True,index_col='date')

set4 = pd.read_csv('flights_2010_000000000003.gzip',compression='gzip',parse_dates=True,index_col='date')

set5 = pd.read_csv('flights_2010_000000000004.gzip',compression='gzip',parse_dates=True,index_col='date')

set6 = pd.read_csv('flights_2010_000000000005.gzip',compression='gzip',parse_dates=True,index_col='date')

In [2]:
combo = pd.concat([set1,set2,set3,set4,set5,set6])

In [3]:
combo.to_csv('combo.gzip',compression='gzip')
print('done')

done

In [5]:
combo.head()

,airline,airline_code,departure_airport,departure_state,departure_lat,departure_lon,arrival_airport,arrival_state,arrival_lat,arrival_lon,departure_schedule,departure_actual,departure_delay,arrival_schedule,arrival_actual,arrival_delay
date,,,,,,,,,,,,,,,,
2012-11-25,US,20355,CLT,NC,35.21,-80.94,PHL,PA,39.87,-75.24,1755.0,1805,10,1931.0,1948,17
2012-11-29,US,20355,CLT,NC,35.21,-80.94,PHL,PA,39.87,-75.24,1755.0,1752,-3,1931.0,1929,-2
2012-11-29,US,20355,CLT,NC,35.21,-80.94,PHL,PA,39.87,-75.24,1445.0,1442,-3,1623.0,1615,-8
2012-11-29,US,20355,CLT,NC,35.21,-80.94,PHL,PA,39.87,-75.24,2005.0,2007,2,2140.0,2139,-1
2012-11-29,US,20355,CLT,NC,35.21,-80.94,PHL,PA,39.87,-75.24,1630.0,1624,-6,1808.0,1805,-3